gerbag_poms/config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :suppliers
 
 

end

gerbag_poms/app/models/customer.rb
class Customer < ActiveRecord::Base
has_many :purchaseorders
has_many :formalquotationscustomers
validates_presence_of :CustomerName
end

gerbag_poms/app/models/supplier.rb
class Supplier < ActiveRecord::Base
has_many :quotationsuppliers
has_many :orders
validates_presence_of :SupplierName
end

gerbag_poms/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	before_action :get_customer, only: [:edit, :update, :destroy, :show]
	def get_customer
		@customer = Customer.find(params[:id])
		
	end


	def show
		
		
		
	end


	def new
		@customer = Customer.new
	end


	def index
		@customers= Customer.all
		@customer = Customer.new(customer_params)
		if @customer.save
		redirect_to customers_path
		end
		
	end

	
	def update
		 @customer.update_attributes(customer_params)
		if @customer.save
		 @count = nil
		 redirect_to customers_path
		end
		
	end


	def edit
		  
	 
	end


	def destroy
		
		@customer.destroy
		redirect_to customers_path
	end




	private
	def customer_params
		params.fetch(:customer, Hash.new ).permit(:CustomerName,:MailingAddress,:ContactPerson,:ContactNumber,:EmailAddress)
		
	end
end

gerbag_poms/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	def index
		
	end
	def new

	end
end

gerbag_poms/app/controllers/quotationsuppliers_controller.rb
class QuotationsuppliersController < ApplicationController
	def show
		@supplier = Supplier.all
		
	end
	def index
		@quotationsuppliers = Quotationsupplier.all
	end
	def new
		@quotationsupplier = Quotationsupplier.new
	end
	def create
		@quotationsupplier = Quotationsupplier.new(quotationsupplier)
		@quotaionsupplier.item_create(params.fetch(:item, Hash.new ).permit(:ItemDescription,:Unit,:Quantity,:Price,:Availability))
	end


	private
	def quotationsupplier_params
		params.fetch(:quotationsupplier, Hash.new ).permit(:SupplierID,:DateRequested,:DateRequired)
		
	end
end

gerbag_poms/app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
	before_action :get_supplier, only: [:edit, :update, :destroy, :show]
	def get_supplier
		@supplier = Supplier.find(params[:id])
		
	end


	def show
		
	end


	def new
		@supplier = Supplier.new
	end

	def index
		@suppliers= Supplier.all
		@supplier = Supplier.new(supplier_params)
		if @supplier.save
		redirect_to suppliers_path
		end
		
	end

	
	def update
		@supplier.update_attributes(supplier_params)
		redirect_to suppliers_path
		
	end


	def edit 

	end


	def destroy
		@supplier.destroy
		redirect_to suppliers_path
	end


	private
	def supplier_params
		params.fetch(:supplier, Hash.new ).permit(:SupplierName,:MailingAddress,:ContactPerson,:ContactNumber,:EmailAddress)
		
	end
end

gerbag_poms/app/views/customers/_form.html.erb
          <div class="col-sm-10 col-md-10 col-xs-12" style="height: 100%; ">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title text-center">Customer's Information</h3>
        </div>
        <div class="panel-body" style="height: 100%; ">
          <div class="panel panel-default">
                      <div class="panel-heading">
                        <h3 class="panel-title text-center">Edit Client</h3>
                      </div>
                      <div class="panel-body">
                        <%= bootstrap_form_for @customer do |f|%>
                          <form class="form-horizontal" role "form">
                           
                            
                            <%= f.text_field :CustomerName, label:"Company Name:", label_class: "control-label"%>
                            
                          
                            
                            <%= f.text_field :MailingAddress, label:"Company Location:", label_class: "control-label"%>
                            <%= f.text_field :ContactPerson, label:"Contact Person:", label_class: "control-label"%>
                            <%= f.text_field :ContactNumber, label:"Cotact Number:", label_class: "control-label"%>
                           
                            
                            <%= f.text_field :EmailAddress, label:"Email Address:", label_class: "control-label"%>
                            
                           
                            <%= f.submit "Submit", class: "btn btn-success"%>
                          </form>
                          <%end%>
                      </div>

                  </div>
        </div>
        <div class="panel-footer"></div>
      </div>
    </div>

gerbag_poms/app/views/customers/index.html.erb
 <div class="col-sm-10 col-md-10 col-xs-12" style="height: 100%; ">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Manage your Customers</h3>
        </div>
        <div class="panel-body" style="height: 100%; ">
         <!--Table Start TABLE TABLE TABLE TABLE-->    
              <div class="container-fluid" >
              <div class="table-responsive" style="height: 100;">
                 
                        <table id="myTable" class=" display select table table-hover table-stripped table-condensed" cellspacing="0" width="100%">
                          <thead>
                          <tr>
                            <th>Company Name</th>
                            <th>Mailing Address</th>
                            <th>Contact Person</th>
                            <th>Contact Number</th>
                            <th>Email Address</th>
                            <th></th>
                            <th></th>
                          </tr>
                          </thead>
                          <tbody>
                          <% @customers.all.each do |customer|%>
                          <tr>
                           
                            <td><%= customer.CustomerName%></td>
                            <td><%= customer.MailingAddress %></td>
                            <td><%= customer.ContactPerson %></td>
                            <td><%= customer.ContactNumber %></td>
                            <td><%= customer.EmailAddress %></td>
                            <td class="display select">
                            <%=  link_to "View",customer,class: "btn btn-info center-block"%>   
                            </td>
                            <td class="display select">
                            <%= button_to "Delete",customer, method: :delete, class: "btn btn-danger"%>
                            </td>
                 <!-- TABLE END -->
                           <%end%>
                          </tr>

                          </tbody>

                      
                        </table>

    <div class="panel-footer">
    <!--ADD NEW CUSTOMER -->

          <div class="col-md-4 col-sm-4 col-xs-12">
            <a class="btn btn-primary center-block" data-toggle="modal" data-target="#mymodal">Add New Customer</a>
              <div class="modal fade" id="mymodal" tabIndex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">

                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                      <h1 style="text-align: center;">Add New Customer</h1>
                    </div>
                    <div class="modal-body">
                      <div class="container-fluid">
                     
                      <form class="form-horizontal" role="form">
                        <%= bootstrap_form_for @customer do |f|%>
                        
                        <div class="form-group"
                          <div class="">          
                            <%= f.text_field :CustomerName, label:"Company Name:", label_class: "control-label"%>
                          
                          </div>
                          <div class="form-group">
                            <%= f.text_field :MailingAddress, label:"Company Location:" ,label_class: "control-label"%>
                          </div>
                          <div class="form-group">
                            <%= f.text_field :ContactPerson, label:"Contact Person:", label_class: "control-label"%>
                          </div>
                          <div class="form-group">
                            <%= f.text_field :ContactNumber, label:"Contact Number:", label_class: "control-label"%>
                          </div>
                          <div class="form-group">
                            <%= f.text_field :EmailAddress, label:"Email Address:", label_class: "control-label"%>
                          </div>
                          <div class="modal-footer">
                            <div class="form-group">        
                            <div class="col-sm-offset-2 col-sm-10">
                             <%= f.submit "Submit", class: "btn btn-success"%>
                              <%end%>
                          </div>
                      </div>
                    </div>
               </form>
            </div>
    </div>
  
        <!-- TABLE END -->
   
                    
                           
                         
                           
                      
                    
                  </div>
                </div>
              </div>
          </div>
           
        <!-- -->
          </div>
         </div>
      </div>
    </div>
  </div>

gerbag_poms/app/views/customers/show.html.erb
<div class="col-sm-10 col-md-10 col-xs-12" style="height: 100%; ">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title text-center">Customer's Information</h3>
        </div>
        <div class="panel-body" style="height: 100%; ">
             <!--Nested Panel-->

              <div>
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h3 class="panel-title text-center"> Customer</h3>
                  </div>
                    <div class="panel-body">
                        <form class="form-horizontal" role"form">
                          <div class="form-group">
                              <label class="control-label col-sm-2" for="Account">Account #:</label>
                              <div class="col-sm-10">
                                  <p class="form-control-static"><%= @customer.CustomerID%></p>
                              </div>
                          </div>
                          
                        </form>
                       
                        <form class="form-horizontal" role"form">

                          <div class="form-group">
                              <label class="control-label col-sm-2" 
                              for="CompanyName">Company Name:</label>
                              <div class="col-sm-10">

                                  <p class="form-control-static">
                                  <%= @customer.CustomerName%></p>
                              </div>
                          </div>
                          
                       
                        <div class="col-md-4 col-md-offset-4">
                                  <%= link_to "Edit",edit_customer_path(@customer),class: "btn btn-warning center-block" %>
                               </div>
                                </form>
                    </div>
                                
                </div>
                      
              </div>
                <div>
                  <div class="panel panel-default">
                      <div class="panel-heading">
                        <h3 class="panel-title text-center">Contact</h3>
                      </div>
                      <div class="panel-body">
                          <form class="form-horizontal" role "form">
                            <div class="form-group">
                              <label class="control-label col-sm-2" for="Contactperson">Contact Person: </label>
                                <div class="col-sm-10">
                                  <p class="form-control-static">
                                  <%= @customer.ContactPerson %></p>
                                </div>
                            </div>
                            
                          </form>
                          <form class="form-horizontal" role "form">
                            <div class="form-group">
                              <label class="control-label col-sm-2" for="Contactnumber">Contact Number: </label>
                                <div class="col-sm-10">
                                  <p class="form-control-static"><%= @customer.ContactNumber %></p>
                                </div>
                            </div>
                            
                          </form>
                           <form class="form-horizontal" role "form">
                            <div class="form-group">
                              <label class="control-label col-sm-2" for="Email">Email Address: </label>
                                <div class="col-sm-10">
                                  <p class="form-control-static">
                                  <%= @customer.EmailAddress %></p>
                                </div>
                            </div>
                            
                          </form>
                          <div class="col-md-3 col-md-offset-3">
                                  <a class="btn btn-primary center-block" href="#">Add</a>
                               </div>
                          <div class="col-md-3">
                                  <%= link_to "Edit",edit_customer_path(@customer),class: "btn btn-warning center-block"%>
                               </div>
                      </div>

                  </div>
                  <div>
                    <div class="panel panel-default">
                    <div class="panel-heading">
                      <h3 class="panel-title text-center">Addresses</h3>
                    </div>
                      <div class="panel-body">
                        <form class="form-horizontal" role "form">
                            <div class="form-group">
                              <label class="control-label col-sm-2" for="Maiiladdress">Mailing Address: </label>
                                <div class="col-sm-10">
                                  <p class="form-control-static">
                                  <%= @customer.MailingAddress %></p>
                                </div>
                            </div>
                            
                          </form>
                         <div class="col-md-3 col-md-offset-3">
                                  <a class="btn btn-primary center-block" href="#">Add</a>
                               </div>
                          <div class="col-md-3">
                                  <%= link_to "Edit",edit_customer_path(@customer),class: "btn btn-warning center-block" %>

                               </div>
                      </div>
                     
                    </div>
                  </div>
                </div>
            <!-- -->
            <!-- Nested Panel -- >
                  
            <!-- -->
        </div>
        <div class="panel-footer"></div>
      </div>
    </div>

gerbag_poms/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gerbag Industrial Technology Philippines</title>
  
  <%= csrf_meta_tags %>
  <!--Stylesheets-->
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "bootstrap.min.css" %>
  <%= stylesheet_link_tag "customerpage.css" %>
  <%= stylesheet_link_tag "buttons.bootstrap.css" %>
  <%= stylesheet_link_tag "select.bootstrap.min.css" %>
  <%= stylesheet_link_tag "jquery.dataTables.min.css" %>
  <%= stylesheet_link_tag "dataTables.bootstrap.min.css" %>
  <!--Stylesheets end-->
  <!--Javascripts-->
  <%= javascript_include_tag 'defaults', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "jquery-2.2.0.min.js" %>
  <%= javascript_include_tag "bootstrap.min.js" %>
  <%= javascript_include_tag "jquery.dataTables.min.js" %>
  <%= javascript_include_tag "dataTables.select..min.js" %>
  <%= javascript_include_tag "customerpage.js"%>
  <%= javascript_include_tag "buttons.print.min.js" %>
  
  <!--Javascripts end-->
</head>
<body>  
<!--Navigation-->
      <nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
        Gerbag
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Hello, Master Gab</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Manange Other Accounts</a></li>
            <li><a href="#">Settings</a></li>
            <li><a href="#">Help</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Log Out</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
        
      </div>
      <div class="jumbotron">
      <div class="container" style="text-align: center;">
        <h1>Hello, Master Bag!</h1>
        <p>Ready to get rich?</p>
      </div>
    </div>
<!--End of Navigation-->

<!--sidebar-->
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2 col-md-2 ">
      <div class="panel-group" id="accordion">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><span class="glyphicon glyphicon-folder-close">
                </span>Customer</a>
            </h4>
          </div>
          <div id="collapseOne" class="panel-collapse collapse in">
            <ul class="list-group">
              <li class="list-group-item"><span class="glyphicon glyphicon-pencil text-primary"></span><a href="CustomerPage.html"><%=link_to "Clients",customers_path%></a></li>

              <li class="list-group-item"><span class="glyphicon glyphicon-flash text-success"></span><a href="#">Quotation</a></li>

              <li class="list-group-item"><span class="glyphicon glyphicon-file text-info"></span><a href="#">Invoice</a></li>
        
         <li class="list-group-item"><span class="glyphicon glyphicon-file text-info"></span><a href="#">Sales</a></li>
             

            </ul>
          </div>
        </div>
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" href="#collapseFour"><span class="glyphicon glyphicon-file">
                </span>Supplier</a>
            </h4>
          </div>
          <div id="collapseFour" class="panel-collapse collapse">
            <div class="list-group">
              <li class="list-group-item"><span class="glyphicon glyphicon-pencil text-primary"></span><a href="CustomerPage.html"><%=link_to "Suppliers",suppliers_path%></a></li>
              <a href="#" class="list-group-item">Quotation</a>
              <a href="#" class="list-group-item">Purchase</a>
              <a href="#" class="list-group-item">Bills</a>
            </div>
          </div>
        </div>
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" href="#collapseFive"><span class="glyphicon glyphicon-heart">
                </span>Reports</a>
            </h4>
          </div>
          <div id="collapseFive" class="panel-collapse collapse">
            <div class="list-group">
              <a href="#" class="list-group-item">
                <h4 class="list-group-item-heading">List group item heading</h4>
                <p class="list-group-item-text">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
              </a>
            </div>
            <div class="list-group">
              <a href="#" class="list-group-item active">
                <h4 class="list-group-item-heading">List group item heading</h4>
                <p class="list-group-item-text">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
              </a>
            </div>
            <div class="list-group">
              <a href="#" class="list-group-item">
                <h4 class="list-group-item-heading">List group item heading</h4>
                <p class="list-group-item-text">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
   


   <%= yield %>



<div class="container">
<footer>
        <p>Gerbag Industrial Technologies 2016 (c)</p>
      </footer>
  </div>
<!--end of sidebar-->
</body>  
</html>

gerbag_poms/app/views/orders/index.html.erb
<div class="col-sm-10 col-md-10 col-xs-12" style="height: 100%; ">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Purchase Order to Suppliers</h3>
        </div>
        <div class="panel-body" style="height: 100%; ">
         <!--Table Start TABLE TABLE TABLE TABLE-->    
              <div class="container-fluid" >
            <div class="table-responsive" style="height: 100;">
                 
                        <table id="myTable" class=" display select table table-hover table-stripped table-condensed" cellspacing="0" width="100%">
                          <thead>
                          <tr>
                           
                            <th>PO #</th>
                            <th>Supplier Name</th>
                            <th>Create Date</th>
                            <th>Grand Total</th>
                            <td></td>
                          </tr>
                          </thead>
                          <tbody>
                          <tr>
                          
                            <td>1</td>
                            <td>Heaven's Door</td>
                            <td>01/12/16</td>
                            <td>1000000</td> 
                            <td class="display select">
                                <div>
                                  <a class="btn btn-info center-block" href="Viewpurchase.html">View</a>
                               </div>
  
          <div>
            <a class="btn btn-danger center-block" data-toggle="modal" data-target="#deletemodal">Delete</a>
              <div class="modal fade" id="deletemodal" tabIndex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">

                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                      <h1 style="text-align: center;">Delete Quotation?</h1>
                    </div>
                    <div class="modal-body">
                      <div class="container-fluid">
                     
                     Are you sure you want to delete quotation?
            </div>

    </div>
  
       
   
                    <div class="modal-footer">
                      <div class="form-group">        
                          <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-danger">Confirm</button>
                          </div>
                        </div>
                    </div>
                    
                  </div>
                </div>
              </div>
          </div>
        <!-- Delete End-->
        
                      
                        </table>
              </div>

    <div class="panel-footer">
    <!--ADD NEW CUSTOMER -->
          <div class="col-md-4 col-sm-4 col-xs-12">
            
            <%= link_to "Add New Purchase", new_order_path,class:"btn btn-primary center-block"%>
            
                              
        </div>
          
         </div>
      </div>
    </div>
    
  </div>
</div>

gerbag_poms/app/views/suppliers/edit.html.erb
<%= render "form" %>

gerbag_poms/app/views/suppliers/show.html.erb
<div class="col-sm-10 col-md-10 col-xs-12" style="height: 100%; ">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title text-center">Supplier's Information</h3>
        </div>
        <div class="panel-body" style="height: 100%; ">
             <!--Nested Panel-->

              <div>
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h3 class="panel-title text-center">Supplier</h3>
                  </div>
                    <div class="panel-body">
                        <form class="form-horizontal" role"form">
                          <div class="form-group">
                              <label class="control-label col-sm-2" for="Account">Account #:</label>
                              <div class="col-sm-10">
                                  <p class="form-control-static"><%= @supplier.SupplierID%></p>
                              </div>
                          </div>
                          
                        </form>
                       
                        <form class="form-horizontal" role"form">

                          <div class="form-group">
                              <label class="control-label col-sm-2" 
                              for="CompanyName">Company Name:</label>
                              <div class="col-sm-10">

                                  <p class="form-control-static">
                                  <%= @supplier.SupplierName%></p>
                              </div>
                          </div>
                          
                       
                        <div class="col-md-4 col-md-offset-4">
                                  <%= link_to "Edit",edit_supplier_path(@supplier),class: "btn btn-warning center-block" %>
                               </div>
                                </form>
                    </div>
                                
                </div>
                      
              </div>
                <div>
                  <div class="panel panel-default">
                      <div class="panel-heading">
                        <h3 class="panel-title text-center">Contact</h3>
                      </div>
                      <div class="panel-body">
                          <form class="form-horizontal" role "form">
                            <div class="form-group">
                              <label class="control-label col-sm-2" for="Contactperson">Contact Person: </label>
                                <div class="col-sm-10">
                                  <p class="form-control-static">
                                  <%= @supplier.ContactPerson %></p>
                                </div>
                            </div>
                            
                          </form>
                          <form class="form-horizontal" role "form">
                            <div class="form-group">
                              <label class="control-label col-sm-2" for="Contactnumber">Contact Number: </label>
                                <div class="col-sm-10">
                                  <p class="form-control-static"><%= @supplier.ContactNumber %></p>
                                </div>
                            </div>
                            
                          </form>
                           <form class="form-horizontal" role "form">
                            <div class="form-group">
                              <label class="control-label col-sm-2" for="Email">Email Address: </label>
                                <div class="col-sm-10">
                                  <p class="form-control-static">
                                  <%= @supplier.EmailAddress %></p>
                                </div>
                            </div>
                            
                          </form>
                          <div class="col-md-3 col-md-offset-3">
                                  <a class="btn btn-primary center-block" href="#">Add</a>
                               </div>
                          <div class="col-md-3">
                                  <%= link_to "Edit",edit_supplier_path(@supplier),class: "btn btn-warning center-block"%>
                               </div>
                      </div>

                  </div>
                  <div>
                    <div class="panel panel-default">
                    <div class="panel-heading">
                      <h3 class="panel-title text-center">Addresses</h3>
                    </div>
                      <div class="panel-body">
                        <form class="form-horizontal" role "form">
                            <div class="form-group">
                              <label class="control-label col-sm-2" for="Maiiladdress">Mailing Address: </label>
                                <div class="col-sm-10">
                                  <p class="form-control-static">
                                  <%= @supplier.MailingAddress %></p>
                                </div>
                            </div>
                            
                          </form>
                         <div class="col-md-3 col-md-offset-3">
                                  <a class="btn btn-primary center-block" href="#">Add</a>
                               </div>
                          <div class="col-md-3">
                                  <%= link_to "Edit",edit_supplier_path(@supplier),class: "btn btn-warning center-block" %>

                               </div>
                      </div>
                     
                    </div>
                  </div>
                </div>
            <!-- -->
            <!-- Nested Panel -- >
                  
            <!-- -->
        </div>
        <div class="panel-footer"></div>
      </div>
    </div>